name: "bashdb CI"
on:
  push:
<<<<<<< HEAD
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    name: "Run Tests on ${{ matrix.os }}"
=======

jobs:
  linux:
    name: "Linux"
    runs-on: ubuntu-latest
    container: bash:5.1
>>>>>>> 11150b3 (Add GitHub Actions to run tests for bash-5.1 in a Docker container)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

<<<<<<< HEAD
      - name: Install dependencies for Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |+
          sudo apt -y update
          sudo apt -y install autoconf automake texinfo

      # - name: Install dependencies for macOS
      #   if: runner.os == 'macOS'
      #   shell: bash
      #   run: |+
      #     brew update
      #     brew install bash
      #     brew install autoconf automake texinfo
      #     # Not installing pygments, because apparently 'osascript' executed during bashdb's init is blocking
      #     # if there's not user logged in.

      # - name: Configure
      #   shell: bash
      #   run: bash ./autogen.sh

      # - name: Test
      #   shell: bash
      #   env:
      #     VERBOSE: 1
      #   run: make -e -j3 check
=======
      - name: Setup Packages
        shell: bash
        run: |+
          apk update
          apk add build-base automake autoconf libtool texinfo

      - name: Configure
        shell: bash
        run: bash ./autogen.sh

      - name: Test
        shell: bash
        env:
          VERBOSE: 1
        run: make -e -j3 check
>>>>>>> 11150b3 (Add GitHub Actions to run tests for bash-5.1 in a Docker container)
